include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce documentation for public members
    public_member_api_docs: true
    # Prefer single quotes for strings
    prefer_single_quotes: true
    # Sort constructor parameters before child/children
    sort_child_properties_last: true
    # Prefer const constructors where possible
    prefer_const_constructors: true
    # Prefer const literals
    prefer_const_literals_to_create_immutables: true
